apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-binding
  namespace: default
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: topics # Optional. Used for input bindings.
    value: "topic1,topic2"
  - name: brokers # Required.
    value:"my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  - name: consumerGroup # Optional. Used for input bindings.
    value: "group1"
  - name: publishTopic # Optional. Used for output bindings.
    value: "topic3"
  - name: authRequired # Required.
    value: "false"
  #- name: saslUsername # Required if authRequired is `true`.
  #  value: "user"
  #- name: saslPassword # Required if authRequired is `true`.
  #  secretKeyRef:
  #    name: kafka-secrets
  #    key: saslPasswordSecret
  - name: initialOffset # Optional. Used for input bindings.
    value: "newest"
  - name: maxMessageBytes # Optional.
    value: 1024
  #- name: version # Optional.
  #  value: 3.2.0